name: run On Time Run.py

on:
  schedule:
    - cron: "* * * * *"  # Jalankan setiap 1 Menit (sesuaikan dengan kebutuhan)
  workflow_dispatch:  # Bisa dijalankan manual dari GitHub Actions
  
#on:
  #push:
    #paths:
      #- '.github/workflows/action.yml'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        run: |
          gh auth status
        with:
          access_token: ${{ github.GH_TOKEN }}

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install rich

      - name: execute py script # run main.py
        env:
          XRP_SECRET: ${{ secrets.XRP_SECRET }}
        run: python Run.py 
