name: run On Time Run.py

on:
  schedule:
    - cron: "* * * * *"  # Jalankan setiap 1 Menit (sesuaikan dengan kebutuhan)
  workflow_dispatch:  # Bisa dijalankan manual dari GitHub Actions
#on:
  #push:
    #paths:
      #- '.github/workflows/action.yml'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Stop Previous Runs
        uses: fkirc/stop-previous-runs@v3
        env:
          GH_TOKEN: ${{ secrets.XRP_SECRET }}
        run: |
          RUNNING_JOBS=$(gh run list --workflow=action.yml --json databaseId,status | jq -r '.[] | select(.status=="in_progress") | .databaseId')
          for JOB_ID in $RUNNING_JOBS; do
            gh run cancel $JOB_ID
          done
          
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install rich

      - name: Setup GitHub CLI
        run: |
          gh auth status || exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: execute py script # run main.py
        env:
          XRP_SECRET: ${{ secrets.XRP_SECRET }}
        run: python Run.py 
